project:
  type: book
  title: "Statistical Computing - Assignment 1"
  output-dir: _site

book:
  title: "Statistical Computing - Assignment 1"
  chapters: 
    - index.qmd
    - Prac_1.qmd
    - Prac_3.qmd
    - Prac_4.qmd


format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    theme: cosmo
    number-sections: false
