project:
  type: site
  title: "Alan Hunter - HNTALA001"
  output-dir: _site

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Prac_1.qmd
        text: Practical 1
      - href: Prac_3.qmd
        text: Practical 3
      - href: Prac_4.qmd
        text: Practical 4

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    theme: cosmo
